- name: Obtener Info sitio
  uri:
    url: https://cloud.redhat.com
    method: GET
    timeout: 30
    status_code: 200
  register: info_pre

- name: imprime
  debug:
    msg:
      - "{{ info_pre }}"

#- name: ENSURE REPORTS FOLDER
#  file:
#    name: reports
#    state: directory

- name: RENDER FACTS AS A REPORT
  template:
    src: Incapsula_templates_Pruebasqa2-to-act-act.j2
    dest: reporte.txt    
