---
- name:  Incapsula pruebasqa
  # 1)
  
  hosts: all
  vars:
    id_sitio: "31700862"
    # sitio id: 31700862 -> pruebas3.qa.bancochile.cl
    string_cdlv: "200.14.133"
    string_lgvl: "200.14.130"
    permiso_conmutar: true

  #connection: local
  gather_facts: true

  tasks:
    - name: Obtener Info sitio
      uri: 
        url: https://cloud.redhat.com
        method: GET
        timeout: 30
        status_code: 200
      register: info_pre

    - name: imprime
      debug:
        msg: 
          - "{{ info_pre }}"

    - name: ENSURE REPORTS FOLDER
      file:
        name: reports
        state: directory
      #delegate_to: localhost
      #run_once: True

    - name: RENDER FACTS AS A REPORT
      template:
        src:  Pruebasqa2-to-act-act.j2
        dest: reports/reporte.txt

    #- name: manda correo
    #  community.general.mail:
    #    host: bchcas006
    #    port: 25
    #    from: alertasansible@bancochile.cl
    #    #to: Jorge Luis Roa Marcano <jroam@bancochile.cl>, canalesinternet@bancochile.cl, Alejandro Daniel Munoz Munoz <admunoz@bancochile.cl>, incapsula_bch@cci-entel.cl, ingenieriasreapps@bancochile.cl, Marco Antonio Serey DelCanto <msereyd@bancochile.cl>
    #    to: Jorge Luis Roa Marcano <jroam@bancochile.cl>
    #    subject: Poner pruebas3.qa.bancochile.cl a activo-activo
    #    body: 'Poner pruebas3.qa.bancochile.cl a activo-activo'
    #    attach: reports/reporte.txt
    #  run_once: True
